"""
CodeExplorationTool — Sandboxed hypothesis testing for Ouroboros.

P3 Gap: Claude can test hypotheses by running code. This tool gives
CONTEXT_EXPANSION the ability to run quick Python snippets in a
sandboxed subprocess to answer questions like "Does this import work?"
or "What does this function return?"

Boundary Principle:
  Deterministic: Subprocess execution (argv, no shell), output capture.
  Agentic: The CODE to explore is generated by the model.

Safety: Subprocess with timeout, bounded output, dangerous pattern blocklist.
"""
from __future__ import annotations

import asyncio
import logging
import os
import sys
import time
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

_TIMEOUT_S = float(os.environ.get("JARVIS_CODE_EXPLORE_TIMEOUT_S", "10"))
_MAX_OUTPUT = int(os.environ.get("JARVIS_CODE_EXPLORE_MAX_OUTPUT", "4096"))
_MAX_PER_ROUND = int(os.environ.get("JARVIS_CODE_EXPLORE_MAX_PER_ROUND", "2"))

_BLOCKED_PATTERNS = frozenset({
    "os.remove", "shutil.rmtree", "os.unlink", "os.system",
    "subprocess.call", "subprocess.run", "subprocess.Popen",
    ".write(", "__import__",
})


@dataclass
class ExplorationResult:
    success: bool
    stdout: str
    stderr: str
    exit_code: int
    duration_s: float
    snippet: str


class CodeExplorationTool:
    """Sandboxed Python snippet execution for hypothesis testing."""

    def __init__(self, project_root: Optional[str] = None) -> None:
        self._project_root = project_root or os.getcwd()

    async def explore(self, snippet: str) -> ExplorationResult:
        """Execute a Python snippet via subprocess (argv, no shell)."""
        t0 = time.monotonic()

        if any(danger in snippet for danger in _BLOCKED_PATTERNS):
            return ExplorationResult(
                success=False, stdout="",
                stderr="BLOCKED: snippet contains dangerous operation",
                exit_code=-3, duration_s=0, snippet=snippet[:500],
            )

        python = os.path.join(self._project_root, "venv", "bin", "python3")
        if not os.path.exists(python):
            python = sys.executable

        try:
            proc = await asyncio.create_subprocess_exec(
                python, "-c", snippet,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=self._project_root,
                env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
            )
            stdout, stderr = await asyncio.wait_for(
                proc.communicate(), timeout=_TIMEOUT_S,
            )
            return ExplorationResult(
                success=(proc.returncode == 0),
                stdout=stdout.decode(errors="replace")[-_MAX_OUTPUT:],
                stderr=stderr.decode(errors="replace")[-_MAX_OUTPUT:],
                exit_code=proc.returncode or 0,
                duration_s=time.monotonic() - t0,
                snippet=snippet[:500],
            )
        except asyncio.TimeoutError:
            return ExplorationResult(
                success=False, stdout="",
                stderr=f"TIMEOUT after {_TIMEOUT_S}s",
                exit_code=-1, duration_s=time.monotonic() - t0,
                snippet=snippet[:500],
            )

    async def explore_batch(self, snippets: List[str]) -> List[ExplorationResult]:
        """Execute multiple snippets sequentially. Bounded."""
        results = []
        for snippet in snippets[:_MAX_PER_ROUND]:
            result = await self.explore(snippet)
            results.append(result)
        return results

    def format_for_prompt(self, results: List[ExplorationResult]) -> str:
        if not results:
            return ""
        lines = ["## Code Exploration Results"]
        for i, r in enumerate(results, 1):
            status = "OK" if r.success else "ERROR"
            lines.append(f"\n### Exploration {i} [{status}]")
            lines.append(f"```python\n{r.snippet}\n```")
            if r.stdout:
                lines.append(f"Output:\n```\n{r.stdout[:1000]}\n```")
            if r.stderr and not r.success:
                lines.append(f"Error:\n```\n{r.stderr[:500]}\n```")
        return "\n".join(lines)
