"""
InlinePermissionGate — per-tool-call deterministic permission classifier.
========================================================================

Slice 1 of the Inline Permission Prompts arc (CC-parity: "is this OK?"
asked inline, per-tool-call, at the boundary of a mutation).

What this module IS
-------------------

A pure-deterministic classifier that takes structured, operator/data-plane
facts about a proposed tool call and returns one of:

    SAFE  — auto-proceed; no prompt needed.
    ASK   — block the tool call; an inline prompt must be rendered.
    BLOCK — hard refuse; no prompt, no proceed.

The classifier is table-driven. The table (``_RULESET``) is the
*load-bearing artifact* of Slice 1 — future slices add ROWS, never change
the primitive API. "Unknown shapes default to ASK" is enforced by the
final RULE_FALLTHROUGH row plus the decide() function's control flow.

What this module IS NOT
-----------------------

* An LLM. No model calls. Zero network I/O. Microsecond per decision.
* A REPL prompter. Slice 2 renders the inline UI. This module only
  emits the *verdict* that tells the REPL whether to prompt.
* A persistence layer. Remembered-allow entries are queried through a
  read-only :class:`RememberedAllowProvider` protocol. Writes belong to
  Slice 3; Slice 1 only consumes the lookup.
* A replacement for existing gates. :class:`PolicyEngine` still runs
  first; :class:`InlinePermissionGate` runs AFTER and may tighten
  (SAFE→ASK, SAFE→BLOCK, NO_MATCH→ASK) but never loosens a BLOCK.

Manifesto alignment
-------------------

* §1 — execution authority is deterministic. The classifier answers the
  authorization question; any "reason" text generated by the model is
  display-only and is never an input here.
* §5 — Tier 0 deterministic fast-path. Pure code, first-match-wins.
* §6 — additive to the Iron Gate. Never weakens an upstream BLOCK.
* §7 — fail-closed: unknown tool shapes default to ASK; autonomous
  routes (BACKGROUND / SPECULATIVE) that would have prompted a human
  are coerced to BLOCK because there is no human on the console.
* §8 — every verdict carries ``rule_id`` and ``ruleset_version`` so
  postmortems can trace exactly which row fired.

Additive taxonomy expansion
---------------------------

New risk shapes land as NEW ROWS in ``_RULESET`` plus NEW TESTS in
``tests/governance/test_inline_permission.py``. The primitive API
(:class:`InlineGateInput`, :class:`InlineGateVerdict`, :func:`decide`)
is frozen for the lifetime of ``inline_permission.v0``. If a future
taxonomy needs fields the current input cannot express, the bump is a
new ruleset version (``inline_permission.v1``) behind a feature flag —
not a reinterpretation of the v0 API.
"""
from __future__ import annotations

import enum
import logging
import re
from dataclasses import dataclass, field
from typing import Callable, List, Optional, Protocol, Tuple, runtime_checkable

logger = logging.getLogger("Ouroboros.InlinePermission")

# ---------------------------------------------------------------------------
# Schema / versioning
# ---------------------------------------------------------------------------

INLINE_PERMISSION_RULESET_VERSION: str = "inline_permission.v0"
"""Telemetry tag; Slice 5 pins this in postmortem logs (§8)."""


# ---------------------------------------------------------------------------
# Public enums
# ---------------------------------------------------------------------------


class InlineDecision(str, enum.Enum):
    """Verdict returned by :func:`decide`."""

    SAFE = "safe"
    ASK = "ask"
    BLOCK = "block"


class RoutePosture(str, enum.Enum):
    """Collapsed view of :class:`ProviderRoute` relevant to prompting.

    We avoid importing :class:`ProviderRoute` directly to keep this
    primitive circular-import-safe and to document that the *only* route
    property the gate cares about is "is there a human who could answer
    an inline prompt?".
    """

    INTERACTIVE = "interactive"
    """Human may be on the console (IMMEDIATE / STANDARD / COMPLEX)."""

    AUTONOMOUS = "autonomous"
    """No human present (BACKGROUND / SPECULATIVE). ASK→BLOCK coercion."""


class UpstreamPolicy(str, enum.Enum):
    """Result from the upstream :class:`PolicyEngine` (or equivalent)."""

    BLOCKED = "blocked"
    APPROVAL_REQUIRED = "approval_required"
    SAFE_AUTO = "safe_auto"
    NO_MATCH = "no_match"


# ---------------------------------------------------------------------------
# Input / verdict dataclasses
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class OpApprovedScope:
    """Structured operator/data-plane facts about what the op-level gate blessed.

    Supplied by the orchestration layer — *never* sourced from model
    output. Model rationales are display-only; authorization inputs are
    the caller's responsibility (§1, §7).
    """

    approved_paths: Tuple[str, ...] = ()
    """Repo-relative POSIX paths (files or directories) the op-level gate
    blessed. A target is "in scope" if it exactly equals one of these or
    is nested under one of them."""

    candidate_hash: str = ""
    """Fingerprint of the candidate the op-level gate actually saw.
    Slice 2+ uses this to detect tool-call-time divergence from the
    blessed candidate."""

    is_read_only: bool = False
    """When True, the enclosing op was declared read-only
    (``OperationContext.is_read_only``). Mirrors ToolExecutor's existing
    ``PolicyContext.is_read_only`` convention."""


@dataclass(frozen=True)
class InlineGateInput:
    """Explicit, structured inputs to a per-tool-call decision.

    All fields must be sourced from orchestration code or the operator,
    never from model claims about "why this is safe".
    """

    tool: str
    """Tool name, e.g. ``"edit_file"`` / ``"bash"`` / ``"read_file"``."""

    arg_fingerprint: str = ""
    """Stable deterministic summary of arguments.

    For ``bash``: the command line. For file-scoped tools: typically the
    target path (the caller may pass ``""``; the gate will fall back to
    ``target_path``). Remembered-allow lookup matches against this."""

    target_path: str = ""
    """Repo-relative POSIX path when the call is file-scoped; ``""`` otherwise.

    Non-empty paths that begin with ``/`` or contain a ``..`` segment are
    classified as ``outside_repo``."""

    route: RoutePosture = RoutePosture.INTERACTIVE
    """§7 fail-closed driver: AUTONOMOUS coerces ASK→BLOCK."""

    approved_scope: OpApprovedScope = field(default_factory=OpApprovedScope)

    upstream_decision: UpstreamPolicy = UpstreamPolicy.NO_MATCH
    """Result of the upstream :class:`PolicyEngine`. BLOCKED mirrors through."""


@dataclass(frozen=True)
class InlineGateVerdict:
    """Verdict returned by :func:`decide`."""

    decision: InlineDecision
    rule_id: str
    reason: str
    ruleset_version: str = INLINE_PERMISSION_RULESET_VERSION


# ---------------------------------------------------------------------------
# RememberedAllowProvider (Slice 3 implements; Slice 1 consumes read-only)
# ---------------------------------------------------------------------------


@runtime_checkable
class RememberedAllowProvider(Protocol):
    """Read-only lookup of operator-remembered allow patterns.

    Slice 1 contract (do not widen in this slice):
        * lookup is read-only and side-effect-free on the gate's path;
        * remembered-allow never overrides a BLOCK rule (only SAFE-ish
          shapes are eligible);
        * persistence / write / expiry / scoping lives in Slice 3.
    """

    def is_pattern_remembered(
        self,
        *,
        tool: str,
        arg_fingerprint: str,
        target_path: str,
    ) -> bool: ...


# ---------------------------------------------------------------------------
# Protected path substrings (mirror of tool_executor._PROTECTED_PATH_SUBSTRINGS
# — kept independent to keep this primitive import-free of the monster module)
# ---------------------------------------------------------------------------

_PROTECTED_PATH_SUBSTRINGS: Tuple[str, ...] = (
    ".git/", "/.git", ".env", "credentials", "secret",
    "node_modules/", ".venv/", "venv/",
    ".ssh/", "id_rsa", "id_ed25519", ".aws/", ".gcp/",
    ".pypirc", ".netrc", ".jarvis/", ".ouroboros/",
)

# Dangerous absolute paths — ``rm -rf`` on any of these is fatal to the host.
_SYSTEM_ROOTS: Tuple[str, ...] = (
    "/", "/*", "~", "$HOME",
    "/bin", "/boot", "/dev", "/etc", "/home", "/lib", "/lib64",
    "/opt", "/proc", "/root", "/sbin", "/srv", "/sys", "/usr", "/var",
)


# ---------------------------------------------------------------------------
# Read-only tool whitelist (file-reading / search / git-inspection family)
# ---------------------------------------------------------------------------

_READ_ONLY_TOOLS: frozenset = frozenset({
    "read_file", "search_code", "get_callers", "glob_files",
    "list_dir", "list_symbols", "git_log", "git_diff", "git_blame",
    "code_explore",
})


# ---------------------------------------------------------------------------
# Bash regexes — compiled once at import time (§5 "<1ms" budget)
# ---------------------------------------------------------------------------

_BASH_SUDO_RX = re.compile(r"(?:^|[\s;&|])sudo\b", re.IGNORECASE)

# curl … | sh / wget … | bash (pipe-to-shell remote-exec)
_BASH_CURL_PIPE_SH_RX = re.compile(
    r"\b(?:curl|wget)\b[^|;&\n]*\|\s*(?:sh|bash|zsh|ksh)\b",
    re.IGNORECASE,
)

# rm -rf in any flag-permutation (-rf / -fr / -rfv / --recursive --force / -r -f / -f -r)
_BASH_RM_RF_RX = re.compile(
    r"\brm\b(?=\s)"
    r"(?:"
    r"\s+[^\s;|&]*(?:-[a-zA-Z]*[rR][a-zA-Z]*[fF][a-zA-Z]*|"
    r"-[a-zA-Z]*[fF][a-zA-Z]*[rR][a-zA-Z]*)"
    r"|"
    r"(?:\s+\S+)*\s+-[rR]\s+-[fF]\b"
    r"|"
    r"(?:\s+\S+)*\s+-[fF]\s+-[rR]\b"
    r"|"
    r"(?:\s+\S+)*\s+--recursive\b(?:\s+\S+)*\s+--force\b"
    r"|"
    r"(?:\s+\S+)*\s+--force\b(?:\s+\S+)*\s+--recursive\b"
    r")",
    re.IGNORECASE,
)

# dd … of=/dev/…  (block-device overwrite)
_BASH_DD_DEVICE_RX = re.compile(r"\bdd\b[^;|&\n]*\bof=/dev/", re.IGNORECASE)

# mkfs / mkfs.ext4 / mkfs.xfs / …
_BASH_MKFS_RX = re.compile(r"\bmkfs(?:\.[a-z0-9]+)?\b", re.IGNORECASE)

# Classic bash fork bomb  :(){ :|:& };:
_BASH_FORK_BOMB_RX = re.compile(r":\(\)\s*\{\s*:\s*\|\s*:\s*&\s*\}\s*;\s*:")

# chmod 777 / or chown -R root / chmod +x on system dirs
_BASH_CHMOD_DANGEROUS_RX = re.compile(
    r"\b(?:chmod|chown)\b[^;|&\n]*\s(?:/|/etc\b|/usr\b|/bin\b|/sbin\b|/lib\b|/var\b|/boot\b)",
    re.IGNORECASE,
)

# git push --force / -f to any branch (blanket ASK; fine-grained remote/branch
# filtering is a Slice 3+ concern)
_BASH_GIT_PUSH_FORCE_RX = re.compile(
    r"\bgit\s+push\b[^;|&\n]*(?:--force\b|--force-with-lease\b|-f\b)",
    re.IGNORECASE,
)

# git reset --hard  (destructive history op)
_BASH_GIT_RESET_HARD_RX = re.compile(
    r"\bgit\s+reset\b[^;|&\n]*--hard\b",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Path-scope classification
# ---------------------------------------------------------------------------


def _path_is_protected(path: str) -> bool:
    if not path:
        return False
    return any(sub in path for sub in _PROTECTED_PATH_SUBSTRINGS)


def _path_is_outside_repo(path: str) -> bool:
    if not path:
        return False
    if path.startswith("/"):
        return True
    parts = path.split("/")
    if ".." in parts:
        return True
    return False


def _path_is_in_approved(path: str, approved: Tuple[str, ...]) -> bool:
    """Return True iff *path* equals, or is nested under, any approved entry."""
    if not path or not approved:
        return False
    for ap in approved:
        if not ap:
            continue
        ap_clean = ap.rstrip("/")
        if path == ap_clean or path.startswith(ap_clean + "/"):
            return True
    return False


# ---------------------------------------------------------------------------
# bash target-path extraction (for rm -rf scope checks)
# ---------------------------------------------------------------------------


def _extract_bash_non_flag_tokens(cmd: str) -> List[str]:
    """Return non-flag tokens from the first statement of a bash command.

    Pragmatic v0 parser: splits on whitespace, stops at first shell-control
    character (``;``, ``&&``, ``||``, ``|``, ``\n``), drops tokens starting
    with ``-``. Sufficient for ``rm -rf <path>`` target detection; future
    slices can swap in a proper shlex-based parser via new rule rows.
    """
    if not cmd:
        return []
    statement: List[str] = []
    for tok in cmd.split():
        if tok in (";", "&&", "||", "|"):
            break
        # Strip embedded control — "foo;bar" collapses to "foo"
        for sep in (";", "&&", "||", "|"):
            if sep in tok:
                tok = tok.split(sep, 1)[0]
        if not tok:
            continue
        statement.append(tok)
    targets = [t for t in statement[1:] if not t.startswith("-")]
    return targets


def _bash_targets_any_system_root(cmd: str) -> bool:
    for tok in _extract_bash_non_flag_tokens(cmd):
        if tok.rstrip("/") in _SYSTEM_ROOTS:
            return True
        # Also catch "/etc/..." style parents
        if tok.startswith("/"):
            for sys_root in _SYSTEM_ROOTS:
                if sys_root.startswith("/") and tok.startswith(sys_root.rstrip("/") + "/"):
                    return True
    return False


def _bash_targets_outside_approved(
    cmd: str,
    approved: Tuple[str, ...],
) -> bool:
    """Return True iff *any* non-flag target in *cmd* is outside approved scope.

    A target is "outside approved" if it is an absolute path, contains ``..``,
    or is a repo-relative path not nested under any approved entry. If the
    command has no targets after the tool name (e.g. ``rm -rf``), we treat
    that as outside approved — a malformed destructive invocation fails closed.
    """
    targets = _extract_bash_non_flag_tokens(cmd)
    if not targets:
        return True
    for t in targets:
        if _path_is_outside_repo(t):
            return True
        if not _path_is_in_approved(t, approved):
            return True
    return False


# ---------------------------------------------------------------------------
# Rule record + matchers
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class InlineRule:
    """A single deterministic row of the v0 ruleset.

    ``matcher`` takes an :class:`InlineGateInput` and returns True iff the
    row fires. Rows are evaluated in declaration order (first-match-wins
    within each decision bucket; see :func:`decide` for the outer order).
    """

    rule_id: str
    decision: InlineDecision
    reason: str
    matcher: Callable[[InlineGateInput], bool]


def _is_bash(inp: InlineGateInput) -> bool:
    return inp.tool == "bash"


def _bash_cmd(inp: InlineGateInput) -> str:
    return inp.arg_fingerprint if _is_bash(inp) else ""


def _always_match(inp: InlineGateInput) -> bool:
    """Terminal fallthrough matcher — always fires (referenced by RULE_FALLTHROUGH)."""
    _ = inp  # structural: v0 matcher signature
    return True


# ---------------------------------------------------------------------------
# THE V0 RULESET — load-bearing artifact. Additive-only; do not renumber.
# ---------------------------------------------------------------------------

_RULESET: Tuple[InlineRule, ...] = (
    # --- BLOCK rows (authorization-final; remembered-allow cannot override) ---
    InlineRule(
        rule_id="RULE_PROTECTED_PATH",
        decision=InlineDecision.BLOCK,
        reason="target path matches protected substring (.env/.git/credentials/ssh/etc.)",
        matcher=lambda i: _path_is_protected(i.target_path),
    ),
    InlineRule(
        rule_id="RULE_BASH_SUDO",
        decision=InlineDecision.BLOCK,
        reason="bash command invokes sudo; O+V never escalates privilege",
        matcher=lambda i: bool(_BASH_SUDO_RX.search(_bash_cmd(i))),
    ),
    InlineRule(
        rule_id="RULE_BASH_CURL_PIPE_SH",
        decision=InlineDecision.BLOCK,
        reason="bash command pipes remote content to a shell (curl|sh / wget|bash)",
        matcher=lambda i: bool(_BASH_CURL_PIPE_SH_RX.search(_bash_cmd(i))),
    ),
    InlineRule(
        rule_id="RULE_BASH_DD_DEVICE",
        decision=InlineDecision.BLOCK,
        reason="bash command overwrites a block device via dd of=/dev/...",
        matcher=lambda i: bool(_BASH_DD_DEVICE_RX.search(_bash_cmd(i))),
    ),
    InlineRule(
        rule_id="RULE_BASH_MKFS",
        decision=InlineDecision.BLOCK,
        reason="bash command invokes mkfs (filesystem format)",
        matcher=lambda i: bool(_BASH_MKFS_RX.search(_bash_cmd(i))),
    ),
    InlineRule(
        rule_id="RULE_BASH_FORK_BOMB",
        decision=InlineDecision.BLOCK,
        reason="bash command matches classic fork-bomb pattern",
        matcher=lambda i: bool(_BASH_FORK_BOMB_RX.search(_bash_cmd(i))),
    ),
    InlineRule(
        rule_id="RULE_BASH_CHMOD_DANGEROUS",
        decision=InlineDecision.BLOCK,
        reason="bash command changes permissions/ownership on a system root path",
        matcher=lambda i: bool(_BASH_CHMOD_DANGEROUS_RX.search(_bash_cmd(i))),
    ),
    InlineRule(
        rule_id="RULE_BASH_RM_RF_SYSTEM_ROOT",
        decision=InlineDecision.BLOCK,
        reason="bash command targets rm -rf at a system root (/, /etc, /usr, ...)",
        matcher=lambda i: bool(
            _BASH_RM_RF_RX.search(_bash_cmd(i))
            and _bash_targets_any_system_root(_bash_cmd(i))
        ),
    ),
    InlineRule(
        rule_id="RULE_BASH_RM_RF_OUT_OF_APPROVED",
        decision=InlineDecision.BLOCK,
        reason="bash command targets rm -rf outside the op-approved scope",
        matcher=lambda i: bool(
            _BASH_RM_RF_RX.search(_bash_cmd(i))
            and _bash_targets_outside_approved(
                _bash_cmd(i), i.approved_scope.approved_paths
            )
        ),
    ),
    InlineRule(
        rule_id="RULE_DELETE_OUT_OF_APPROVED",
        decision=InlineDecision.BLOCK,
        reason="delete_file target is outside the op-approved scope",
        matcher=lambda i: (
            i.tool == "delete_file"
            and bool(i.target_path)
            and not _path_is_in_approved(
                i.target_path, i.approved_scope.approved_paths
            )
        ),
    ),

    # --- SAFE rows (cannot weaken a BLOCK above; remembered-allow is equivalent) ---
    InlineRule(
        rule_id="RULE_READ_ONLY_TOOLS",
        decision=InlineDecision.SAFE,
        reason="tool is in the read-only / inspection whitelist",
        matcher=lambda i: i.tool in _READ_ONLY_TOOLS,
    ),
    InlineRule(
        rule_id="RULE_RUN_TESTS",
        decision=InlineDecision.SAFE,
        reason="run_tests executes pytest in-repo under the ToolExecutor sandbox",
        matcher=lambda i: i.tool == "run_tests",
    ),
    InlineRule(
        rule_id="RULE_WEB_FETCH",
        decision=InlineDecision.SAFE,
        reason="web_fetch is HTTP GET only; no mutation on local state",
        matcher=lambda i: i.tool == "web_fetch",
    ),
    InlineRule(
        rule_id="RULE_WEB_SEARCH",
        decision=InlineDecision.SAFE,
        reason="web_search is a read-only query against the search provider",
        matcher=lambda i: i.tool == "web_search",
    ),
    InlineRule(
        rule_id="RULE_EDIT_IN_APPROVED",
        decision=InlineDecision.SAFE,
        reason="edit_file target is within the op-approved scope",
        matcher=lambda i: (
            i.tool == "edit_file"
            and bool(i.target_path)
            and _path_is_in_approved(
                i.target_path, i.approved_scope.approved_paths
            )
        ),
    ),
    InlineRule(
        rule_id="RULE_WRITE_IN_APPROVED",
        decision=InlineDecision.SAFE,
        reason="write_file target is within the op-approved scope",
        matcher=lambda i: (
            i.tool == "write_file"
            and bool(i.target_path)
            and _path_is_in_approved(
                i.target_path, i.approved_scope.approved_paths
            )
        ),
    ),

    # --- ASK rows (may be coerced to BLOCK under AUTONOMOUS route) ---
    InlineRule(
        rule_id="RULE_EDIT_OUT_OF_APPROVED",
        decision=InlineDecision.ASK,
        reason="edit_file target diverges from the op-approved scope",
        matcher=lambda i: (
            i.tool == "edit_file"
            and bool(i.target_path)
            and not _path_is_in_approved(
                i.target_path, i.approved_scope.approved_paths
            )
        ),
    ),
    InlineRule(
        rule_id="RULE_WRITE_OUT_OF_APPROVED",
        decision=InlineDecision.ASK,
        reason="write_file target diverges from the op-approved scope",
        matcher=lambda i: (
            i.tool == "write_file"
            and bool(i.target_path)
            and not _path_is_in_approved(
                i.target_path, i.approved_scope.approved_paths
            )
        ),
    ),
    InlineRule(
        rule_id="RULE_DELETE_IN_APPROVED",
        decision=InlineDecision.ASK,
        reason="delete_file target is in scope but deletion is irreversible",
        matcher=lambda i: (
            i.tool == "delete_file"
            and bool(i.target_path)
            and _path_is_in_approved(
                i.target_path, i.approved_scope.approved_paths
            )
        ),
    ),
    InlineRule(
        rule_id="RULE_BASH_RM_RF_IN_APPROVED",
        decision=InlineDecision.ASK,
        reason="bash rm -rf targets are in scope but recursive delete is irreversible",
        matcher=lambda i: bool(
            _BASH_RM_RF_RX.search(_bash_cmd(i))
            and not _bash_targets_outside_approved(
                _bash_cmd(i), i.approved_scope.approved_paths
            )
        ),
    ),
    InlineRule(
        rule_id="RULE_BASH_GIT_PUSH_FORCE",
        decision=InlineDecision.ASK,
        reason="bash command force-pushes git history; confirm target remote/branch",
        matcher=lambda i: bool(_BASH_GIT_PUSH_FORCE_RX.search(_bash_cmd(i))),
    ),
    InlineRule(
        rule_id="RULE_BASH_GIT_RESET_HARD",
        decision=InlineDecision.ASK,
        reason="bash command runs git reset --hard; discards local work",
        matcher=lambda i: bool(_BASH_GIT_RESET_HARD_RX.search(_bash_cmd(i))),
    ),
    InlineRule(
        rule_id="RULE_BASH_UNKNOWN",
        decision=InlineDecision.ASK,
        reason="bash invocation did not match a known SAFE or BLOCK row",
        matcher=lambda i: i.tool == "bash",
    ),
    # Fallthrough: unknown tool shape. Must be last.
    InlineRule(
        rule_id="RULE_FALLTHROUGH",
        decision=InlineDecision.ASK,
        reason="unknown tool/arg shape; fail-closed to human confirmation",
        matcher=_always_match,
    ),
)


def ruleset() -> Tuple[InlineRule, ...]:
    """Return the active v0 ruleset (immutable)."""
    return _RULESET


# ---------------------------------------------------------------------------
# decide() — the single public entry point
# ---------------------------------------------------------------------------


_UPSTREAM_BLOCK_VERDICT = InlineGateVerdict(
    decision=InlineDecision.BLOCK,
    rule_id="RULE_UPSTREAM_BLOCKED",
    reason="PolicyEngine upstream decision is BLOCKED; inline gate mirrors",
)


def decide(
    inp: InlineGateInput,
    *,
    remembered: Optional[RememberedAllowProvider] = None,
) -> InlineGateVerdict:
    """Classify a proposed tool call.

    Order of evaluation (§6 "additive, never weakens"):

    1. If ``inp.upstream_decision`` is BLOCKED → mirror BLOCK.
    2. Walk :data:`_RULESET` in order. The first matching row wins for
       BLOCK. For SAFE rows, remembered-allow is consulted first so that
       operator-remembered patterns bypass *only* SAFE/ASK territory —
       never BLOCK.
    3. If a matched row is ASK and ``inp.route`` is AUTONOMOUS, coerce
       to BLOCK with a rule_id prefix of ``"autonomous_coerce:"`` so
       telemetry can distinguish prompt-suppression-fail-closed from a
       hard-BLOCK row.

    Returns
    -------
    InlineGateVerdict
        ``decision`` is SAFE / ASK / BLOCK. ``rule_id`` identifies the
        row that fired; ``ruleset_version`` pins
        :data:`INLINE_PERMISSION_RULESET_VERSION` for §8 postmortems.
    """
    if inp.upstream_decision is UpstreamPolicy.BLOCKED:
        return _UPSTREAM_BLOCK_VERDICT

    # First pass: look for a BLOCK match. BLOCKs always win over remembered-allow.
    for rule in _RULESET:
        if rule.decision is InlineDecision.BLOCK and rule.matcher(inp):
            return InlineGateVerdict(
                decision=InlineDecision.BLOCK,
                rule_id=rule.rule_id,
                reason=rule.reason,
            )

    # Second pass: remembered-allow (SAFE-scope only).
    if remembered is not None:
        try:
            if remembered.is_pattern_remembered(
                tool=inp.tool,
                arg_fingerprint=inp.arg_fingerprint or inp.target_path,
                target_path=inp.target_path,
            ):
                return InlineGateVerdict(
                    decision=InlineDecision.SAFE,
                    rule_id="RULE_REMEMBERED_ALLOW",
                    reason="operator-remembered allow pattern (Slice 3 store)",
                )
        except Exception as exc:  # noqa: BLE001
            # A broken provider must never escalate privilege. Log and ignore.
            logger.warning(
                "RememberedAllowProvider raised; ignoring: %s", exc,
            )

    # Third pass: SAFE/ASK rows in declaration order.
    for rule in _RULESET:
        if rule.decision is InlineDecision.BLOCK:
            continue
        if not rule.matcher(inp):
            continue
        if rule.decision is InlineDecision.ASK and inp.route is RoutePosture.AUTONOMOUS:
            return InlineGateVerdict(
                decision=InlineDecision.BLOCK,
                rule_id=f"autonomous_coerce:{rule.rule_id}",
                reason=(
                    "autonomous route cannot render an inline prompt; "
                    f"original ASK reason: {rule.reason}"
                ),
            )
        return InlineGateVerdict(
            decision=rule.decision,
            rule_id=rule.rule_id,
            reason=rule.reason,
        )

    # Cannot happen — RULE_FALLTHROUGH always matches. Defensive fallback.
    return InlineGateVerdict(
        decision=InlineDecision.BLOCK
        if inp.route is RoutePosture.AUTONOMOUS
        else InlineDecision.ASK,
        rule_id="RULE_FALLTHROUGH_DEFENSIVE",
        reason="ruleset exhausted without match (should not occur)",
    )


# ---------------------------------------------------------------------------
# InlinePermissionGate — thin object wrapper (injectable for tests / Slice 2)
# ---------------------------------------------------------------------------


class InlinePermissionGate:
    """Thin object wrapper around :func:`decide`.

    Slice 2 will inject an instance of this into the tool-executor hook
    point. Slice 1 keeps the object boundary narrow — ruleset is frozen
    module-level, :class:`RememberedAllowProvider` is injected, decide
    is a pass-through. No hidden state.
    """

    def __init__(
        self,
        *,
        remembered: Optional[RememberedAllowProvider] = None,
    ) -> None:
        self._remembered = remembered

    def classify(self, inp: InlineGateInput) -> InlineGateVerdict:
        return decide(inp, remembered=self._remembered)
